name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  chatview:
    path: ../
  wechat_assets_picker:
  waveform_recorder:
  flutter_chat_bubble:
  video_player:
  voice_message_package:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
