name: chatease
description: "Flutter package that provides a prebuilt, feature-rich chat screen designed to simplify development while offering powerful capabilities"
version: 1.0.3
homepage: https://github.com/yajatkaul/ChatEase

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  waveform_recorder: ^1.4.0
  voice_message_package: ^2.2.1
  wechat_assets_picker: ^9.4.2
  flutter_chat_bubble: ^2.0.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
